apiVersion: apps/v1
kind: Deployment  
metadata:
    labels:
      app: lamp
    name: lamp-wp
    namespace: default
spec:
    selector:
      matchLabels:
        app: lamp
        tier: frontend
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: lamp
          tier: frontend
      spec:
        containers:
        - env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: mysql-root-pass
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                key: database
                name: mysql-db-url
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                key: username
                name: mysql-user-pass
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: mysql-user-pass
          - name: MYSQL_HOST
            valueFrom:
              secretKeyRef:
                key: host
                name: mysql-host
          image: wordpress:php7.4-apache
          name: httpd-php-wp-container
          ports:
          - containerPort: 80
            name: httpd
            protocol: TCP
          volumeMounts:
          - mountPath: /var/www/html
            name: lamp-persistent-storage
        - env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: mysql-root-pass
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                key: database
                name: mysql-db-url
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                key: username
                name: mysql-user-pass
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: mysql-user-pass
          - name: MYSQL_HOST
            valueFrom:
              secretKeyRef:
                key: host
                name: mysql-host
          image: mysql:5.6
          name: mysql-container
          ports:
          - containerPort: 3306
            name: mysql
            protocol: TCP
          volumeMounts:
          - mountPath: /var/www/html
            name: lamp-persistent-storage
        volumes:
        - name: lamp-persistent-storage
          persistentVolumeClaim:
            claimName: lamp-pv-claim
