apiVersion: v1
kind: Service
metadata:
  labels:
    app: lamp
  name: lamp-service
  namespace: default
spec:
  ports:
  - nodePort: 30008
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: lamp
    tier: frontend
  type: LoadBalancer
status:
  loadBalancer: {}
