apiVersion: v1
kind: Service
metadata:
  labels:
    app: lamp
  name: mysql-service
  namespace: default
spec:
  ports:
  - nodePort: 30009
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: lamp
    tier: frontend
  type: LoadBalancer
status:
  loadBalancer: {}
