apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    labels:
      app: lamp
    name: lamp-pv-claim
    namespace: default
spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 550Mi
    storageClassName: standard
    volumeMode: Filesystem
